export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';

export const HOTEL_DETAIL_REQUEST = 'HOTEL_DETAIL_REQUEST';
export const HOTEL_DETAIL_SUCCESS = 'HOTEL_DETAIL_SUCCESS';
export const HOTEL_DETAIL_FAIL = 'HOTEL_DETAIL_FAIL';
